version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: ventu_test
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: ventu_test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
